/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash.phonebook;

import java.util.HashMap;
import java.util.Arrays;
import java.util.Comparator;
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        String[] input = {"97674223", "119", "1195524421"};

        System.out.println(solution(input));
    }

    public static boolean solution(String[] phone_book){
        boolean answer = true;

        System.out.println(Arrays.toString(phone_book));

        Arrays.sort(phone_book, Comparator.comparingInt(String::length));

        System.out.println(Arrays.toString(phone_book));
        
        solution:
        for(int i = 0; i < phone_book.length; i++){
            for(int z = phone_book.length-1; z > i; z--){
                if(phone_book[z].indexOf(phone_book[i]) == 0){
                    answer = false;
                    break solution;
                }
            }
        }


        return answer;
    }
}
